on:
  pull_request:
    branches:
      - "main"
  push:
    tags:
      - "*"

env:
  REGISTRY: "git.fruzit.pp.ua"

permissions:
  contents: "read"
  id-token: "write"
  packages: "write"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout"
        uses: "https://github.com/actions/checkout@v4.2.2"
        with:
          fetch-depth: 1

        # TODO: https://github.com/catthehacker/docker_images/issues/112
      - name: "Install QEMU"
        run: |
          sudo apt-get update
          sudo apt-get install -y "qemu-user-static"

      # - name: "Set up QEMU"
      #   uses: "https://github.com/docker/setup-qemu-action@v3.6.0"

      - name: "Set up Docker buildx"
        uses: "https://github.com/docker/setup-buildx-action@v3.10.0"

      - name: "Login to Container Registry"
        uses: "https://github.com/docker/login-action@v3.4.0"
        if: "github.event_name != 'pull_request'"
        with:
          # TODO: https://codeberg.org/forgejo/forgejo/issues/1296
          password: "${{ secrets.FORGEJO_TOKEN }}"
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.repository_owner }}"

      - name: Extract Docker metadata
        uses: "https://github.com/docker/metadata-action@v5.7.0"
        id: "docker_meta"
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/web
          labels: |
            org.opencontainers.image.description=Weather WEB application that allows users to subscribe to weather updates for their city
            org.opencontainers.image.licenses=MIT License
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch
            type=ref,event=pr
            type=schedule
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: "Build and push Docker image"
        uses: "https://github.com/docker/build-push-action@v6.16.0"
        id: "build-and-push"
        with:
          context: "."
          file: "./contrib/docker/Dockerfile"
          labels: "${{ steps.docker_meta.outputs.labels }}"
          platforms: "linux/amd64,linux/arm64"
          push: "${{ github.event_name != 'pull_request' }}"
          tags: "${{ steps.docker_meta.outputs.tags }}"
