// This file is auto-generated by @hey-api/openapi-ts

export type Weather = {
    /**
     * Current temperature
     */
    temperature?: number;
    /**
     * Current humidity percentage
     */
    humidity?: number;
    /**
     * Weather description
     */
    description?: string;
};

export type Subscription = {
    /**
     * Email address
     */
    email: string;
    /**
     * City for weather updates
     */
    city: string;
    /**
     * Frequency of updates
     */
    frequency: 'hourly' | 'daily';
    /**
     * Whether the subscription is confirmed
     */
    confirmed?: boolean;
};

export type GetWeatherData = {
    body?: never;
    path?: never;
    query: {
        /**
         * City name for weather forecast
         */
        city: string;
    };
    url: '/weather';
};

export type GetWeatherErrors = {
    /**
     * Invalid request
     */
    400: unknown;
    /**
     * City not found
     */
    404: unknown;
};

export type GetWeatherResponses = {
    /**
     * Successful operation - current weather forecast returned
     */
    200: {
        /**
         * Current temperature
         */
        temperature?: number;
        /**
         * Current humidity percentage
         */
        humidity?: number;
        /**
         * Weather description
         */
        description?: string;
    };
};

export type GetWeatherResponse = GetWeatherResponses[keyof GetWeatherResponses];

export type SubscribeData = {
    body: {
        /**
         * Email address to subscribe
         */
        email: string;
        /**
         * City for weather updates
         */
        city: string;
        /**
         * Frequency of updates (hourly or daily)
         */
        frequency: 'hourly' | 'daily';
    };
    path?: never;
    query?: never;
    url: '/subscribe';
};

export type SubscribeErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Email already subscribed
     */
    409: unknown;
};

export type SubscribeResponses = {
    /**
     * Subscription successful. Confirmation email sent.
     */
    200: unknown;
};

export type ConfirmSubscriptionData = {
    body?: never;
    path: {
        /**
         * Confirmation token
         */
        token: string;
    };
    query?: never;
    url: '/confirm/{token}';
};

export type ConfirmSubscriptionErrors = {
    /**
     * Invalid token
     */
    400: unknown;
    /**
     * Token not found
     */
    404: unknown;
};

export type ConfirmSubscriptionResponses = {
    /**
     * Subscription confirmed successfully
     */
    200: unknown;
};

export type UnsubscribeData = {
    body?: never;
    path: {
        /**
         * Unsubscribe token
         */
        token: string;
    };
    query?: never;
    url: '/unsubscribe/{token}';
};

export type UnsubscribeErrors = {
    /**
     * Invalid token
     */
    400: unknown;
    /**
     * Token not found
     */
    404: unknown;
};

export type UnsubscribeResponses = {
    /**
     * Unsubscribed successfully
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://weatherapi.app/api' | 'https://weatherapi.app/api' | (string & {});
};