// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zWeather = z.object({
    temperature: z.number().optional(),
    humidity: z.number().optional(),
    description: z.string().optional()
});

export const zSubscription = z.object({
    email: z.string(),
    city: z.string(),
    frequency: z.enum([
        'hourly',
        'daily'
    ]),
    confirmed: z.boolean().optional()
});

export const zGetWeatherResponse = z.object({
    temperature: z.number().optional(),
    humidity: z.number().optional(),
    description: z.string().optional()
});